services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    ports:
      - "50051:50051"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
